# Generated by Django 2.2.7 on 2019-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Drink')),
                ('volume', models.IntegerField(default=0, verbose_name='Volume, ml')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price, hrn')),
            ],
        ),
    ]
