# Generated by Django 2.2.7 on 2019-11-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ingredient')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('weight', models.IntegerField(verbose_name='grams')),
                ('Is_vegan', models.BooleanField(verbose_name='Vegan')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pizza')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('weight', models.IntegerField(verbose_name='grams')),
            ],
        ),
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Ingredients')),
                ('pizza_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza_name')),
            ],
        ),
    ]
