# Generated by Django 2.2.7 on 2019-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191111_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='pizzas',
            name='ingredients',
            field=models.ManyToManyField(to='pizza.Ingredients'),
        ),
    ]
