# Generated by Django 2.2.7 on 2019-11-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20191111_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Pizzas',
            new_name='Pizza',
        ),
    ]
