# Generated by Django 2.2.7 on 2019-11-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20191111_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryFields',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity in order')),
                ('is_vegan', models.BinaryField(max_length=1, verbose_name='Vegan(1 or 0)')),
                ('is_meat', models.BooleanField(verbose_name='Meat')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('order_execution_time', models.DurationField(verbose_name='Order execution time')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('bill_pdf', models.FileField(upload_to='', verbose_name='PDF of bill')),
                ('package_image', models.ImageField(height_field=100, upload_to='', verbose_name='Package image')),
                ('order_label', models.SlugField(verbose_name='Label')),
                ('url', models.URLField(verbose_name='URL')),
                ('additional_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Ingredient')),
                ('name', models.ManyToManyField(to='pizza.Pizza_name')),
            ],
        ),
    ]
