# Generated by Django 2.2.7 on 2019-11-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_everyfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EveryFields',
        ),
    ]
