# Generated by Django 2.2.7 on 2019-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_delete_everyfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Every',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield', models.CharField(max_length=256)),
            ],
        ),
    ]
