# Generated by Django 2.2.7 on 2019-11-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20191117_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='every',
            name='text',
            field=models.TextField(default='0'),
        ),
    ]
