# Generated by Django 2.2.7 on 2019-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_every_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='every',
            name='positiveInteger',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
