# Generated by Django 2.2.7 on 2019-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_every_positiveinteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='every',
            name='binary',
            field=models.BinaryField(null=True),
        ),
    ]
