# Generated by Django 2.2.7 on 2019-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_every_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='every',
            name='boolean',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='file',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='every',
            name='filePath',
            field=models.FilePathField(null=True, path=None),
        ),
        migrations.AddField(
            model_name='every',
            name='float_f',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='every',
            name='genericIPAdress',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='every',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
