# Generated by Django 2.2.7 on 2019-11-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_auto_20191117_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='every',
            name='integerfield',
            field=models.IntegerField(default=1, null=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(null=None, verbose_name='grams'),
        ),
        migrations.AlterField(
            model_name='pizza_name',
            name='weight',
            field=models.IntegerField(null=None, verbose_name='grams'),
        ),
        migrations.CreateModel(
            name='PizzaOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(choices=[(1, 'Thin'), (2, 'Medium'), (3, 'Thick')], default=1, max_length=50, verbose_name='Base thickness')),
                ('additional_sauce', models.CharField(choices=[('GA', 'Garlick sauce'), ('TO', 'Tomato sauce'), ('NO', 'No sauce needed')], default='TO', max_length=50, verbose_name='Additional sauce')),
                ('namber', models.IntegerField(default=1, verbose_name='Pizza number')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza')),
            ],
        ),
    ]
