# Generated by Django 2.2.7 on 2019-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_auto_20191118_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='every',
            old_name='filePath',
            new_name='file_Path',
        ),
        migrations.RenameField(
            model_name='every',
            old_name='genericIPAdress',
            new_name='generic_IP_adress',
        ),
        migrations.RenameField(
            model_name='every',
            old_name='positiveInteger',
            new_name='positive_integer',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Is_vegan',
            new_name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='every',
            name='integerfield',
        ),
        migrations.AddField(
            model_name='every',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='every',
            name='integer_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='every',
            name='binary',
            field=models.BinaryField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='every',
            name='boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='every',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Weight, grams'),
        ),
        migrations.AlterField(
            model_name='pizza_name',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Weight, grams'),
        ),
        migrations.AlterField(
            model_name='pizzaordered',
            name='side_name',
            field=models.CharField(choices=[('S', 'Thin'), ('M', 'Medium'), ('L', 'Thick')], default='S', max_length=50, verbose_name='Base thickness'),
        ),
    ]
