# Generated by Django 2.2.7 on 2019-11-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0015_auto_20191119_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_name',
            new_name='PizzaName',
        ),
        migrations.RenameField(
            model_name='pizzaordered',
            old_name='namber',
            new_name='number',
        ),
    ]
